### ISSUE TITLE
Filter Error

### ISSUE THREAD

**Issue by MartynBSpooner** [ONS-OpenData/ONS_CPA#1]
File "/usr/local/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 448, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, out)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:

[0;31mFilterError[0m: more than one match for given filter(s)
FilterError: more than one match for given filter(s)

**Comment by ajtucker** [comment]
These filter errors are due to the ONS web pages changing and the scraper not being able to distinguish between the different downloads.

Fixing gss-cogs/gss-utils#2 may fix this.

**Comment by mikeAdamss** [comment]
going to look at https://github.com/GSS-Cogs/gss-utils/issues/2

**Comment by mikeAdamss** [comment]
fixed via on the the scraper updates.
